### ISSUE TITLE
running spec on a windows machine has 9 failed test

### ISSUE THREAD

**Issue by StefanSchoof** [mefellows/vagrant-dsc#29]
Running `bundle exec rake spec` on a windows 10 machine result into 9 Failures. (On Ubuntu everything is fine.) 1 to 4 and 8 sound like no problem in the plugin itself. For the other I am unsure if they are a test bugs or not.
```
Failures:

  1) VagrantPlugins::DSC::Config derived settings should detect the fully qualified path to the manifest automatically
     Failure/Error: expect(subject.expanded_configuration_file.to_s).to eq("#{subject.temp_dir}/manifests/MyWebsite.ps1")

       expected: "/tmp/vagrant-dsc-15/manifests/MyWebsite.ps1"
            got: "C:/tmp/vagrant-dsc-15/manifests/MyWebsite.ps1"

       (compared using ==)
     # ./spec/provisioner/config_spec.rb:76:in `block (3 levels) in <top (required)>'

  2) VagrantPlugins::DSC::Config validate should generate a module path on the host machine relative to the Vagrantfile
     Failure/Error: expect(subject.expanded_module_paths('/path/to/vagrant/')).to eq(["/path/to/vagrant/foo/modules"])

       expected: ["/path/to/vagrant/foo/modules"]
            got: ["C:/path/to/vagrant/foo/modules"]

       (compared using ==)
     # ./spec/provisioner/config_spec.rb:101:in `block (3 levels) in <top (required)>'

  3) VagrantPlugins::DSC::Config validate should generate a module path on the host machine relative to the Vagrantfile with relative paths
     Failure/Error: expect(subject.expanded_module_paths('/path/to/vagrant/')).to eq(["/path/to/modules"])

       expected: ["/path/to/modules"]
            got: ["C:/path/to/modules"]

       (compared using ==)
     # ./spec/provisioner/config_spec.rb:106:in `block (3 levels) in <top (required)>'

  4) VagrantPlugins::DSC::Config validate should generate module paths on the host machine relative to the Vagrantfile
     Failure/Error: expect(subject.expanded_module_paths('/path/to/vagrant/')).to eq(["/path/to/vagrant/dont/exist", "/path/to/vagrant/also/dont/exist"])

       expected: ["/path/to/vagrant/dont/exist", "/path/to/vagrant/also/dont/exist"]
            got: ["C:/path/to/vagrant/dont/exist", "C:/path/to/vagrant/also/dont/exist"]

       (compared using ==)
     # ./spec/provisioner/config_spec.rb:111:in `block (3 levels) in <top (required)>'

  5) VagrantPlugins::DSC::Config validate should be invalid if 'manifests_path' is not a real directory
     Failure/Error: raise "Error #{error} was not raised" if !errors["dsc provisioner"].include? error

     RuntimeError:
       Error "Path to DSC Manifest folder does not exist: /i/do/not/exist" was not raised
     # ./spec/base.rb:43:in `assert_error'
     # ./spec/provisioner/config_spec.rb:117:in `block (3 levels) in <top (required)>'

  6) VagrantPlugins::DSC::Config validate should be invalid if 'configuration_file' is not a real file
     Failure/Error: raise "Error #{error} was not raised" if !errors["dsc provisioner"].include? error

     RuntimeError:
       Error "Path to DSC Manifest does not exist: /notexist.ps1" was not raised
     # ./spec/base.rb:43:in `assert_error'
     # ./spec/provisioner/config_spec.rb:124:in `block (3 levels) in <top (required)>'

  7) VagrantPlugins::DSC::Config validate should be invalid if 'configuration_data_file' is not a real file
     Failure/Error: raise "Error #{error} was not raised" if !errors["dsc provisioner"].include? error

     RuntimeError:
       Error "Path to DSC Configuration Data file does not exist: /oeu/aoeu/notexist.psd1" was not raised
     # ./spec/base.rb:43:in `assert_error'
     # ./spec/provisioner/config_spec.rb:131:in `block (3 levels) in <top (required)>'

  8) VagrantPlugins::DSC::Config validate should detect the fully qualified path to the configuration data file automatically
     Failure/Error: expect(subject.expanded_configuration_data_file.to_s).to eq("#{subject.temp_dir}/manifests/foo.psd1")

       expected: "/tmp/vagrant-dsc-22/manifests/foo.psd1"
            got: "C:/tmp/vagrant-dsc-22/manifests/foo.psd1"

       (compared using ==)
     # ./spec/provisioner/config_spec.rb:145:in `block (3 levels) in <top (required)>'

  9) VagrantPlugins::DSC::Config validate should be invalid if 'module_path' is not a real directory
     Failure/Error: raise "Error #{error} was not raised" if !errors["dsc provisioner"].include? error

     RuntimeError:
       Error "Path to DSC Modules does not exist: /i/dont/exist" was not raised
     # ./spec/base.rb:43:in `assert_error'
     # ./spec/provisioner/config_spec.rb:151:in `block (3 levels) in <top (required)>'

```

**Comment by mefellows** [comment]
Ahh, yes - they're not the most portable tests!

I'm actually going to guess they are all related to paths. The `Error "Path to DSC Configuration Data file does not exist: /oeu/aoeu/notexist.psd1" was not raised` is probably because the path that doesn't exist starts with `c:` or something - might need to add a debug or see what exception is raised.

In any case, I'm happy for you to submit a PR that does the following:

1. Makes the tests portable (maybe regex/paramaterise the paths?)
2. Setup a build for appveyor / another Windows provider so that we can run CI for updates.

**Comment by mefellows** [comment]
I'm going to close this thanks to your great work.
